### ISSUE TITLE
X-Client-Info

### ISSUE THREAD

**Issue by awalias** [marcelobarreto/supabase-rb#1]
we're rolling out a header similar to Stripe's App-Data in all of the client libs so issues can be debugged more easily between the client and the backend

the javascript libs are done already: supabase/supabase-js#238

the format is: X-Client-Info: supabase-js/1.11.0

for client libs that wrap others (like how supabase-js wraps gotrue-js) we allow the wrapper lib to overwrite the wrapped lib's header (given that we can infer the gotrue-js version based on which supabase-js was used to make the call)

any help with rolling this out here would be incredible, it also ideally would be rolled out into any wrapped libs (gotrue-rb etc.)

**Comment by marcelobarreto** [comment]
I can do it on this weekend ;)

**Comment by awalias** [comment]
assigned you in case you're still keen @marcelobarreto but no worries if you're busy!

**Comment by marcelobarreto** [comment]
done @awalias

**Comment by awalias** [comment]
Amazing! @marcelobarreto thanks a ton 👏
